src/components/Button/AIRecommendationButton/index.tsx, src/components/Button/CheckBusLocationButton/index.tsx
- vercel 배포 build 오류 해결
- 없음
- #40 
- 소요 시간: 5분 => 이미 해결 완료.
=> fix: icon import 경로 build 에러 수정

src/components/Button/AIRecommendationButton/index.tsx, src/components/Button/CheckBusLocationButton/index.tsx
- vercel로 배포하는 과정에서 build 오류를 해결하여 머지 합니다.
=> [FE] vercel build오류 해결 반영 Frontend dev => front 브랜치 코드 머지

.github/workflows/frontend-action1.yml
=> [FE] - 배포용 깃헙 액션 수정

backend/src/main/java/com/ddbb/dingdong/application/common/Params.java, backend/src/main/java/com/ddbb/dingdong/application/common/UseCase.java
usecase의 공통요소를 인터페이스로 분리하여 협업시 코드의 통일성을 높이고 개발생산성을 높입니다.
구현사항
예상 소요 시간: 1시간
목표 기간: 02월 04일 ~ 02월 04일
=> [BE] UseCase 인터페이스 구현

backend/src/main/java/com/ddbb/dingdong/application/common/Params.java, backend/src/main/java/com/ddbb/dingdong/application/common/UseCase.java, backend/src/main/java/com/ddbb/dingdong/application/exception/APIException.java, backend/src/main/java/com/ddbb/dingdong/application/exception/InvalidParamErrorInfo.java, backend/src/main/java/com/ddbb/dingdong/application/exception/InvalidParamException.java, backend/src/main/java/com/ddbb/dingdong/application/exception/handler/WebMvcExceptionHandler.java, backend/src/main/java/com/ddbb/dingdong/domain/common/exception/DomainException.java, backend/src/main/java/com/ddbb/dingdong/domain/common/exception/ErrorInfo.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/auth/encrypt/SHA512PasswordEncoder.java, backend/src/test/java/com/ddbb/dingdong/auth/SHA512PasswordEncoderTest.java
=> [BE] 1주차 스프린트 backend 브랜치 동기화

src/App.tsx, src/pages/MyPage/page.tsx, src/pages/MyPage/styles.ts, src/pages/Reservations/page.tsx, src/pages/Reservations/styles.ts, src/styles/colors.ts
=> Feat/#80 my page 생성

src/App.tsx, src/pages/MyPage/page.tsx, src/pages/MyPage/styles.ts, src/pages/Reservations/page.tsx, src/pages/Reservations/styles.ts, src/styles/colors.ts
https://github.com/softeer5th/team1-dingdong/issues/80
- 마이 페이지 구현
=> [FE] Feat/#80 my page 생성

backend/src/main/java/com/ddbb/dingdong/application/usecase/user/GetHomeLocationUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/user/entity/Home.java, backend/src/main/java/com/ddbb/dingdong/domain/user/entity/User.java, backend/src/main/java/com/ddbb/dingdong/domain/user/repository/UserQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/user/repository/UserRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/user/repository/projection/HomeLocationProjection.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/user/home/UserHomeEndpoint.java, backend/src/test/java/com/ddbb/dingdong/user/GetHomeLocationUseCaseTest.java
=> [BE] 유저의 희망 탑승지 정보 조회 API 구현

backend/src/main/java/com/ddbb/dingdong/domain/user/service/UserManagement.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/auth/AuthEndpoint.java
=> [BE] 로그인 API 수정

backend/src/main/java/com/ddbb/dingdong/domain/transportation/entity/Line.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/entity/Path.java
=> [fix]: 직선 경로 정보(Line) 추가에 따른 Entity 설계 수정

backend/src/main/java/com/ddbb/dingdong/domain/transportation/entity/Line.java
- Line Entity에 List import문이 빠진 채로 merge되어 이를 추가했습니다.
=> [BE] Line Entity 누락 부분 수정

backend/src/main/java/com/ddbb/dingdong/domain/reservation/service/ReservationManagement.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/ReservationController.java
등교 서비스는 8:00 ~ 18:00 까지만 예약이 가능하도록,
하교 서비스는 11:00 ~ 21:00 까지만 예약이 가능하도록 검증하는 로직 이 존재하지 않아서, 이를 추가하였습니다
=> [BE] 예매 API 수정 사항

backend/.gitignore, backend/build.gradle, backend/src/main/java/com/ddbb/dingdong/domain/clustering/api/ApiKeyManager.java, backend/src/main/java/com/ddbb/dingdong/domain/clustering/api/RouteOptimizationApiClient.java, backend/src/main/java/com/ddbb/dingdong/domain/clustering/api/TmapApiKeyManager.java, backend/src/main/java/com/ddbb/dingdong/domain/clustering/api/TmapApiProperties.java, backend/src/main/java/com/ddbb/dingdong/domain/clustering/api/TmapRouteOptimizationApiClient.java, backend/src/main/java/com/ddbb/dingdong/domain/clustering/config/ClusteringConfig.java, backend/src/main/java/com/ddbb/dingdong/domain/clustering/service/BusRouteCreationService.java, backend/src/main/java/com/ddbb/dingdong/domain/clustering/service/ClusteringSchedulerService.java, backend/src/main/java/com/ddbb/dingdong/domain/clustering/service/ElkiClusteringService.java, backend/src/main/java/com/ddbb/dingdong/domain/clustering/util/ClusteringUtil.java, backend/src/main/java/com/ddbb/dingdong/domain/clustering/util/HaversineDistanceFunction.java, backend/src/main/java/com/ddbb/dingdong/domain/clustering/util/RouteOptimizationDTOConverter.java, backend/src/main/java/com/ddbb/dingdong/domain/clustering/util/TmapRouteOptimizationDTOConverter.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/entity/Line.java, backend/src/main/resources/application.yml, backend/src/test/java/com/ddbb/dingdong/domain/clustering/ApiClientTest.java
=> [BE] 경로 최적화 작업 단위를 단일 클러스터 단위로 변경

backend/src/main/java/com/ddbb/dingdong/application/usecase/bus/SubscribeBusUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/bus/UnsubscribeBusUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/BusErrors.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/BusSubscribeService.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/simulator/subscription/BusSubscriptionManager.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/simulator/subscription/publisher/PeriodicBusPublisher.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/simulator/subscription/subscriber/SocketSubscriber.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/webSocket/handler/SocketHandler.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/bus/SubscriptionEndPoint.java, backend/src/main/java/com/ddbb/dingdong/util/FormatUtil.java
- #106
- 어떤 버스 위치를 받아올 수 있도록 구독하는 API를 구현했습니다,
- 버스가 아직 출발하지 않았더라도 구독이 가능하며 대기상태에 있다가, 버스가 출발하면 대기 상태에 있는 구독자들을 모두 등록하여 대기 상태에 있는 구독자들이 바로 정보를 받을 수 있게 구현했습니다.
- 버스 출발 시간과 구독자의 구독 타이밍이 겹쳐, 출발 전에 구독한 구독자가 출발 후에 정보를 받아올 수 없는 경우가 없도록 동기화 처리를 했습니다.
=> [BE] - 버스 구독 API

src/main.tsx
- createLoader 함수 내에서 발생하는 type에러 수정 완료.
=> fix: main.tsx createLoader 수정 타입 수정

backend/src/main/java/com/ddbb/dingdong/application/usecase/bus/GetAvailableBusLine.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/bus/GetPathPointLine.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/BusScheduleQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/BusStopQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/PathQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/projection/AvailableBusStopProjection.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/projection/BusReservedSeatProjection.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/projection/PathPointProjection.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/BusStopQueryService.java, backend/src/main/java/com/ddbb/dingdong/domain/user/repository/UserQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/user/repository/projection/HomeStationProjection.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/bus/BusController.java
- #132
- 홈 화면의 실시간 버스 화면과 함께타기에서 사용할 경로 좌표 조회 API를 구현합니다.
- 버스 스케쥴 아이디로 조회합니다.
=> [BE] 경로 조회 API

backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/MakeGeneralReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/MakeTogetherReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/RequestGeneralReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/RequestTogetherReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/error/ReservationInvalidParamErrors.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/entity/Reservation.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/BusStopRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/service/ReservationErrors.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/service/ReservationManagement.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/entity/BusSchedule.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/BusScheduleQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/BusErrors.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/BusScheduleManagement.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/auth/encrypt/TokenManager.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/ReservationController.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/exchanges/GeneralReservationConfirmDTO.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/exchanges/GeneralReservationRequestDTO.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/exchanges/TogetherReservationConfirmDTO.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/exchanges/TogetherReservationRequestDTO.java
=> [BE] 함께 타기 예매 API 구현

backend/src/main/java/com/ddbb/dingdong/ApplicationInitializer.java, backend/src/main/java/com/ddbb/dingdong/domain/user/repository/SchoolRepository.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/user/UserController.java
1. School Entity 의 Cascade 변경에 따른 ApplicationInitializer 코드 수정
2. 여분의 테스트 계정 자동 회원가입 로직 추가 (30개)
=> [BE] ApplicationInitializer 수정

backend/src/main/java/com/ddbb/dingdong/application/usecase/auth/LogoutUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/auth/SignUpUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/auth/errors/AuthParamErrors.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/user/PutHomeLocationUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/auth/service/AuthErrors.java, backend/src/main/java/com/ddbb/dingdong/domain/auth/service/AuthManagement.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/auth/AuthController.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/user/exchanges/UpdateHomeLocationDto.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/user/exchanges/UserHomeEndpoint.java
=> [BE] 로그아웃 API 구현

backend/src/main/java/com/ddbb/dingdong/application/exception/handler/WebMvcExceptionHandler.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/MakeGeneralReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/MakeTogetherReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/RequestGeneralReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/RequestTogetherReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/routing/CreateRouteUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/service/ReservationManagement.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/entity/BusSchedule.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/BusScheduleQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/BusErrors.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/BusScheduleManagement.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/auth/encrypt/TokenErrors.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/auth/encrypt/TokenManager.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/routing/api/ApiKeyManager.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/ReservationController.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/exchanges/TogetherReservationRequestDTO.java, backend/src/main/resources/application-local.yml, backend/src/test/java/com/ddbb/dingdong/auth/PaymentTokenTest.java
=> [BE] 버그 수정 및 리팩토링

backend/src/main/java/com/ddbb/dingdong/domain/auth/service/AuthManagement.java, backend/src/main/java/com/ddbb/dingdong/domain/user/service/UserManagement.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/auth/AuthUser.java
- 현재 AuthUser에는 userId만 저장되어서 controller에서 주입받아 사용할 수 있음.
- schoolId도 userId처럼 회원가입시 변하지 않는 값이므로, 세션 객체에 넣어도 무방하다고 판단함.
=> [BE] AuthUser에 school Id 추가

backend/src/main/java/com/ddbb/dingdong/application/usecase/auth/SignUpUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/auth/errors/AuthParamErrors.java, backend/src/main/java/com/ddbb/dingdong/domain/auth/service/AuthErrors.java, backend/src/main/java/com/ddbb/dingdong/domain/auth/service/AuthManagement.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/auth/AuthController.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/auth/exchanges/SignUpRequestDto.java
=> [BE] 회원가입 API Body값 수정

backend/src/main/java/com/ddbb/dingdong/application/usecase/user/GetSchoolsUseCase.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/auth/configuration/WebConfig.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/user/SchoolController.java
서버에 저장된 모든 학교 리스트를 반환 (schoolId와 학교명) 하는 API를 구현하였습니다
=> [feat] 학교 리스트 반환하는 api 구현

backend/.dockerignore, backend/.gitignore, backend/build.gradle, backend/docker-compose.yml, backend/dockerfile, backend/src/main/java/com/ddbb/dingdong/infrastructure/auth/configuration/WebConfig.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/swagger/SwaggerConfig.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/admin/exchanges/CreateClusterRequestDTO.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/admin/exchanges/GetLocationRequestDTO.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/bus/BusController.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/ReservationController.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/exchanges/GeneralReservationConfirmDTO.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/exchanges/GeneralReservationRequestDTO.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/exchanges/TogetherReservationConfirmDTO.java
- API의 날짜 타입을 모두 ISO 형식으로 받도록 수정했습니다.
- 필요없는 필드와 Enum 클래스를 삭제했습니다.
=> [BE] 날짜 API ISO 타입으로 통일

backend/src/main/java/com/ddbb/dingdong/application/usecase/notification/GetNotificationsUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/notification/repository/NotificationQueryRepository.java
=> [BE] 알림 조회 긴급 버그 수정

src/api/query/users/index.ts, src/components/Loading/index.tsx, src/hooks/useNavigate/index.ts, src/loader/createLoader.tsx, src/main.tsx, src/middleware.tsx
- middleware.tsx: 미들웨어 정리(인증 여부, 세션 존재 여부)
- createLoader.tsx: 통합 에러 처리를 위한 loader 생성 함수
- Loading: 리팩토링
- main.tsx: 미들웨어 추가, createLoader.tsx 변경에 따른 수정
- useNavigate: sessionStorage + navigate 결합 hook
=> [FE] Router Middleware, Loader 관련 기능 수정

backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/MakeGeneralReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/MakeTogetherReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/RequestGeneralReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/error/ReservationInvalidParamErrors.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/ReservationQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/ReservationRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/service/ReservationErrors.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/service/ReservationManagement.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/auth/encrypt/Token.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/auth/encrypt/TokenErrors.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/auth/encrypt/TokenManager.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/auth/encrypt/TokenRepository.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/exchanges/GeneralReservationRequestDTO.java
- query문에 reservation status를 pending, allocated 상태인것만 중복 예약으로 간주하도록 코드를 수정하였습니다.
=> [BE] 중복 예매 체크 로직의 버그 수정

backend/src/main/java/com/ddbb/dingdong/application/usecase/user/GetUserInfoUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/user/repository/UserQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/user/repository/projection/UserStaticOnly.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/auth/AuthController.java
- #216 
- #217 
- 내 정보 조회 시 학교의 위도 경도를 전달하도록 변경하였습니다.
- 로그인 확인 전용 엔드포인트를 추가했습니다.  (아무것도 하지 않고, 세션만 확인합니다.)
- 로그인 확인할 때는 세션만 확인하는데 별도로 유효성 검증 로직이 필요하면 추가해야 합니다.
=> [BE] 내 정보 반환 시 학교 정보도 반영되도록 수정 / 로그인 확인 엔드포인트 추가 #218

backend/src/main/java/com/ddbb/dingdong/application/usecase/user/GetWalletBalanceUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/payment/repository/WalletProjectionRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/payment/repository/projection/BalanceProjection.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/user/UserController.java
- #195 
- 사용자의 딩동 머니 잔액을 조회하는 API를 구현했습니다.
- 수정하기 위해 조회하는 것이 아닌 정말로 읽기만 하는 작업이기에 따로 락을 설정하지 않았습니다.
=> [BE] 남은 딩동 머니 조회 API

backend/src/main/java/com/ddbb/dingdong/application/usecase/auth/SignUpUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/auth/service/AuthManagement.java
- `SignUpUseCase.java`에서, 회원가입 성공 시 `authenticateManager.setAuthentication()`을 호출해 로그인 세션을 부여하도록 수정
=> [BE] 회원가입시 자동으로 로그인 되도록 세션 쿠키 부여

backend/.database/schema.sql, backend/src/main/java/com/ddbb/dingdong/application/usecase/user/ChargeDingdongMoneyFreeUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/payment/entity/Wallet.java, backend/src/main/java/com/ddbb/dingdong/domain/payment/entity/vo/DingdongMoneyUsageType.java, backend/src/main/java/com/ddbb/dingdong/domain/payment/repository/WalletRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/payment/service/PaymentErrors.java, backend/src/main/java/com/ddbb/dingdong/domain/payment/service/PaymentManagement.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/user/UserController.java
=> [BE] 딩동머니 무료 충전 API 구현

backend/src/main/java/com/ddbb/dingdong/application/usecase/user/CheckFreeChargeAvailableUseCase.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/user/UserController.java
=> [BE] 무료 충전 사용 가능한지 여부 조회 API 구현

backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/GetUserBusScheduleInfoUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/ReservationQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/ReservationController.java
- 버스가 운행중, 운행 대기 상태인것만 조회하고, 운행 종료된 것은 반환하지 않습니다.
=> [BE] 유저의 버스 배차 정보 조회 API

backend/src/main/java/com/ddbb/dingdong/application/usecase/bus/StartBusUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/BusScheduleManagement.java
- 어드민이 버스를 출발시키면, 그 출발 시킨 시간을 기준으로 버스가 학교에 도착하는 예상시간이 바뀌게됩니다.
=> [feat] 버스 스케쥴에 예상 도착시간을 변경하는 도메인 메소드

backend/.database/schema.sql, backend/src/main/java/com/ddbb/dingdong/application/usecase/bus/StartBusUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/routing/CreateRouteUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/clustering/entity/Location.java, backend/src/main/java/com/ddbb/dingdong/domain/notification/repository/NotificationQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/notification/service/NotificationEventListener.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/BusStopQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/projection/UserIdAndReservationIdProjection.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/BusScheduleManagement.java
- 버스 알림 타입이 `BUS_START` 일 때는 실제 버스 시간표대로 알림을 가져오도록 구현
- 버스 알림 타입이 `BUS_START`가 아닐떄는 이상적인 버스 시간표대로 알림을 가져오도록 구현
- 등교 버스일때만 버스 출발 알림을 처리하도록 구현
=> [BE] 버스 알림 버그 수정 및 버스 출발 알림 event listner 구현

backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/ReservationController.java
=> [BE] 이미 예매한 중복 일정에 대한 예매 시도 시, 에러 코드 반환 세분화

backend/src/main/java/com/ddbb/dingdong/application/exception/handler/WebMvcExceptionHandler.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/configuration/WebConfig.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/webSocket/handler/AuthHandShakeInterceptor.java
- CORS 설정에서 포트를 선택적으로 적을 수 있게 변경했습니다.
- 로그를 적절한 때에 적절한 양만 찍도록 수정하였습니다.
=> [BE] 배포 설정

backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/GetUserBusScheduleInfoUseCase.java
- 기존엔 Reservation 테이블에서 가져왔지만, 실제 바뀐 Arrival/Departure Time 으로 가져오도록 수정
=> [BE] 실제 바뀐 Arrival/Departure Time 으로 가져오도록 수정

backend/src/main/java/com/ddbb/dingdong/application/usecase/user/TestFCMNotificationUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/BusScheduleQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/projection/BusStopArrivalTime.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/BusScheduleManagement.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/notification/NotificationMessageFormatter.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/notification/WebPushNotificationEventListener.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/notification/firebase/FCMPushNotificationSender.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/user/UserController.java
- #287 
- 버스 아이디들로 조회하여 같은 버스 도착 시간을 공유하는 유저 아이디를 종합하여 버스 출발 메시지를 알림을 전송합니다.
- 토큰을 테스트 하기 위한 API를 구현했습니다.
=> [BE] 버스 출발 웹 푸시 메시지 전송

backend/src/main/java/com/ddbb/dingdong/domain/notification/repository/NotificationQueryRepository.java
- left join시에 문제가 발생하여 모든 값이 null로반환되는 것이었음, left join을 없애고 select절에서 서브쿼리를 통해 버그 해결
=> [BE] 배차 실패 알림  query 버그 수정

backend/src/main/java/com/ddbb/dingdong/domain/reservation/service/ReservationManagement.java
##
- 시간 기준이아니라 , 날짜기준으로 현재날짜 + 2일 ~ 현재날짜 + 2일 + 2달 로 변경하였습니다.
=> [BE] 일반 예매 가능 날짜 정책 변경

backend/src/main/java/com/ddbb/dingdong/infrastructure/auth/encrypt/token/CachedTokenProvider.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/cache/SimpleCache.java, backend/src/test/java/com/ddbb/dingdong/auth/TokenConcurrentTest.java
- Simple Cache를 Bean 주입해서 모두가 쓸수있게하고, 제네릭이 아닌 Object 타입으로 받도록 변경
- 모두가 하나의 Cache를 공유합니다
=> [BE] Simple Cache를 Bean 주입해서 모두가 쓸수있게하고, 제네릭이 아닌 Object 타입으로 받도록 변경

src/route/index.tsx
=> fix: 충돌 해결

src/api/webPushNotification/notification.ts, src/pages/Auth/Login/index.tsx, src/pages/Auth/Signup/UserInfo/index.tsx, src/pages/BusBooking/CustomRouteBooking/components/SelectTimeBottomModal/index.tsx, src/pages/BusBooking/CustomRouteBooking/components/TimeViewBottomModal/index.tsx, src/pages/BusBooking/FixedRouteBookingSelectBus/components/MapWrapper/index.tsx, src/pages/BusBooking/FixedRouteBookingSelectBus/page.tsx, src/pages/BusBooking/store/actions.ts, src/pages/BusBooking/store/reducer.ts, src/pages/BusBooking/store/types.ts, src/pages/Home/component/BusSelection/styles.ts, src/utils/fcmToken/fcmTokenStorage.ts, src/utils/signUp/userInfoFormatValidation.ts, src/webPushNotification/handleAllowNotification.ts, src/webPushNotification/settingFCM.ts
#326 
fcm 웹 푸시 알림 처리를 하다가 로그인을 해야 토큰 생성이 가능하다는 것을 놓쳐서
토큰 생성 후 로컬 스토리지에 저장후, 로그인이나 회원가입 요청 성공 후 토큰을 서버로 보내도록 수정을 했습니다.
일부 QA도 조금 반영해뒀습니다.
=> [FE] - FCM 토큰 생성 요청 처리 수정

backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/RequestTogetherReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/ReservationQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/service/ReservationConcurrencyManager.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/cache/SimpleCache.java
- 쿼리 페이지네이션에서 totalElements가 원래와다름
- query문과 countQuery가 서로 다른 것으로 확인이 되었음.
- 두 개를 일치시켜 버그를 해결함.
=> [BE] 한 유저가 한 버스 스케쥴에 여러번 토큰 요청시, 게속 버스 좌석을 점유하는 버그 수정

backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/SuggestReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/user/entity/Timetable.java, backend/src/main/java/com/ddbb/dingdong/domain/user/entity/User.java, backend/src/main/java/com/ddbb/dingdong/util/ParamValidator.java
- 패스워드 정규식에서 대문자 1개 이상 필수 조건을 삭제하였습니다.
- 시간표 기반 추천에서, 유저 시간표가 등록되지 않았을 경우, null을 반환하도록 수정하였습니다.
=> [BE] 패스워드 정규식 수정 및 시간표 기반 예매 추천 형식 변경

README.md
=> [FE] docs: README.md에 FE 위키 추가

backend/src/main/java/com/ddbb/dingdong/infrastructure/lock/StoppableSemaphore.java
=> [BE] StoppableSemaphore - tryAcquire 로직 수정

backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/MakeTogetherReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/service/ReservationManagement.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/cache/SimpleCache.java
- 함께 타기 예약시 lock ,unlock대신 semaphore만 사용하도록 변경
- 시간표추천 정책 변경 , maxDate을 2일추가
=> [BE] 함께타기 예약 확정시 lock , unlock 로직 제거 및 시간표 추천 정책 변경

backend/src/main/java/com/ddbb/dingdong/infrastructure/auth/encrypt/utils/AESEncoder.java, backend/src/main/resources/application-local.yml
- 기존 하드코딩되어있던 Secret을 환경변수로 분리합니다.
=> [BE] AES SECRET을 환경변수로 분리

backend/.database/schema.sql, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/subscription/publisher/PeriodicBusPublisher.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/notification/firebase/MessageFactory.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/notification/firebase/entity/FCMToken.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/webSocket/handler/AuthHandShakeInterceptor.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/webSocket/handler/SocketHandler.java
- fcm 전송 시 url 링크 첨부
- fcm 토큰 유니크 제약조건 변경
- socket 관련 설정 수정
=> FCM, 소켓 관련 수정

frontend/src/pages/BusBooking/CustomRouteBooking/components/TimeViewBottomModal/index.tsx, frontend/src/pages/BusBooking/CustomRouteBooking/components/TimeViewBottomModal/styles.ts
=> design: 선택한 일정 클릭 영역을 아이콘에서 전체 button으로 확장

frontend/src/pages/SocketLayout/utils/deleteItem.ts, frontend/src/pages/Wallet/utils/addRefundHistory.ts
=> Frontend dev

frontend/src/pages/TimetableManagement/components/TimePicker/index.tsx
오전 12, 오후 12 -> 12, 24로 표기되던거 수정
=> fix: 오전 오후 12시 수정

frontend/src/constants/signupTexts.ts, frontend/src/pages/BusBooking/CustomRouteBooking/components/CalendarView/index.tsx, frontend/src/pages/BusBooking/CustomRouteBooking/components/TimeViewBottomModal/styles.ts, frontend/src/pages/BusBooking/FixedRouteBooking/Components/FixedBookingCalendarView/index.tsx, frontend/src/pages/BusBooking/FixedRouteBooking/page.tsx, frontend/src/pages/BusBooking/hooks/useCalendar.ts, frontend/src/utils/calendar/calendarUtils.ts
- 달력 좌우 이동 여러번 이동 시=> 월 표시가 변동되지 않는 부분 해결
- 함께타기 스케줄이 없는 경우 다른 달로 이동 가능한 문제 => 없는 경우는 이동하지 못하도록 수정
- 회원가입시, 가이드 텍스트에서 영 대문자 부분은 뺌.
=> fix: 버그 수정
