backend/src/main/java/com/ddbb/dingdong/infrastructure/auth/encrypt/SHA512PasswordEncoder.java, backend/src/test/java/com/ddbb/dingdong/auth/SHA512PasswordEncoderTest.java
`{반복횟수}${base64Salt값}${비밀번호 해시 결과}`
`12$abc$abcd`
이경우 반복횟수는 2^12 = 4096이고, salt값은 abc, 비밀번호 해시결과는 abcd입니다. 
참고로 base64는 $를 포함하지 않기때문에 구분자를 $로 정하게 되었습니다.
결론만 말하자면 큰 문제가 없습니다
https://jhkimmm.tistory.com/24
Spring Security의 BcryptPasswordEncoder도 salt값을 해시값과 함께 저장하고있다고 합니다.
=> [BE] 비밀번호 암호화 util 클래스 구현

backend/src/main/java/com/ddbb/dingdong/application/exception/APIErrorInfos.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/auth/LoginUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/user/LoginUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/user/UserInvalidParamErrors.java, backend/src/main/java/com/ddbb/dingdong/domain/user/repository/UserRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/user/service/UserErrors.java, backend/src/main/java/com/ddbb/dingdong/domain/user/service/UserManagement.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/auth/UserLoginEndpoint.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/auth/dto/LoginRequest.java
- LoginUsecase.java에서, 유저가 건네준 값중 빈 값이 있는지 확인 후 비어 있다면 예외를 던지도록 구현 하였습니다.
- LoginEndpoint.java에서, 도메인 로직에서 발생한 예외를 try catch 잡아, 최종적으로 HttpStats.UNAUTHORIZED를 반환하도록 구현하였습니다.
- UserManagement.java의 login 메소드에서 로그인이 성공하면 HttpSession에 유저를 추가하도록 구현하였습니다.
- 현재 login 메소드에서는 평문 비밀번호와 비교를 하지만, 추후에 비밀번호를 encrypt하여 비교하는 방식을 도입해야 합니다.
=> [BE] 로그인 API 구현

backend/src/main/java/com/ddbb/dingdong/application/exception/APIErrorInfos.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/user/GetUserInfoUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/user/LoginUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/user/UserInvalidParamErrors.java, backend/src/main/java/com/ddbb/dingdong/domain/user/entity/User.java, backend/src/main/java/com/ddbb/dingdong/domain/user/repository/UserQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/user/repository/UserReadOnlyRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/user/repository/UserRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/user/repository/projection/UserStaticOnly.java, backend/src/main/java/com/ddbb/dingdong/domain/user/service/UserErrors.java, backend/src/main/java/com/ddbb/dingdong/domain/user/service/UserManagement.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/auth/UserLoginEndpoint.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/auth/dto/LoginRequest.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/user/UserController.java, backend/src/test/java/com/ddbb/dingdong/domain/user/repository/userRepository/GetStaticInfoTest.java
- UserController.java에서, 도메인 로직에서 발생한 예외를 try catch 잡아, 최종적으로 HttpStats.UNAUTHORIZED를 반환하도록 구현하였습니다.
- UserReadOnlyRepository.java에서 필요한 필드만 가져올 수 있도록 인터페이스 projection을 이용해 구현하였습니다.
- GetUserInfoUseCase는 UserReadOnlyRepository을 직접 참조하여 구현합니다.
=> [BE] - 유저 정보 조회 API 구현

backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/GetReservationsUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/ReservationQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/user/entity/User.java
=> [BE] 유저 조회 쿼리 수정 및 User Entity 변경

src/lib/customNav/index.tsx, src/pages/Home/page.tsx
- usePathQueries(): 라우터 경로에 맞게 설정한 쿼리 배열을 실행 후 return
- navigate({state:}): navigate에 state 전달 가능
=> [FE] feat: 커스틈 nav 기능 추가

backend/build.gradle, backend/src/main/java/com/ddbb/dingdong/infrastructure/webSocket/CustomCloseStatus.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/webSocket/configuration/WebSocketConfig.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/webSocket/handler/AuthHandShakeInterceptor.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/webSocket/handler/SocketHandler.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/webSocket/repository/SocketRepository.java
- #22
- 소켓을 관리하는 SocketRepository를 구현했습니다.
- 유저 아이디 하나당 하나의 소켓만을 유지합니다. 새로운 소켓 연결 요청이 들어온다면 기존 소켓은 연결을 해제하고 새 연결을 유지합니다.
- 스케쥴 서비스(경로 작성 로직)에서 많은 양의 데이터를 다루게 되므로,  메모리를 최대한 아끼는 것이 맞다고 판단했습니다.
- 소켓 하나를 가지고 여러 데이터를 보내게 되므로 보낼 때 대기해야 하는 시간이 있을 수 있지만 동시에 보내는 데이터는 많아야 2~3개 정도기 때문에 큰 문제는 되지 않는다고 생각했습니다.
=> [BE] 소켓 매니저 구현

backend/src/main/java/com/ddbb/dingdong/application/usecase/notification/CheckUnreadNotificationUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/notification/GetNotificationsUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/MakeGeneralReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/clustering/entity/Location.java, backend/src/main/java/com/ddbb/dingdong/domain/notification/entity/Notification.java, backend/src/main/java/com/ddbb/dingdong/domain/notification/entity/vo/NotificationType.java, backend/src/main/java/com/ddbb/dingdong/domain/notification/repository/NotificationQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/notification/repository/NotificationRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/notification/repository/projection/NotificationProjection.java, backend/src/main/java/com/ddbb/dingdong/domain/notification/service/NotificationEventListener.java, backend/src/main/java/com/ddbb/dingdong/domain/notification/service/NotificationManagement.java, backend/src/main/java/com/ddbb/dingdong/domain/notification/service/error/NotificationErrors.java, backend/src/main/java/com/ddbb/dingdong/domain/payment/service/PaymentManagement.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/service/ReservationManagement.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/service/event/AllocationFailedEvent.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/service/event/AllocationSuccessEvent.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/entity/BusSchedule.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/notification/NotificationController.java
- #154 
- 예매 실패, 예매 성공시 발행한 event를 수신하고있는 event listener를 구현하여, 알림을 저장하는 기능을 구현했습니다.
(따로 api를 호출하는것이아닌, 예매 실패/성공 시 자동적으로 알림이 저장됩니다)
알림이 저장되고나서, socket.sendMessage를 통해 "alarm"이라는 텍스트메세지를 전달합니다.
- 안읽은 메세지가 있는지 boolean으로 반환할수 있는 HTTP API를 구현하였습니다.
- 알림 내역조회를 페이지네이션으로 반환하는 API를 구현하였습니다. 해당 API를 호출하면, 그 당시 있던 알림은 모두 read처리가 되게 됩니다.
- 버스 출발에 대한 알림 listener를 구현하지 않았습니다.
- @ji-woong-song 님이 버스 출발을 구현해주신 이후에 추가 할 예정입니다.
=> [BE] 알림 기능 구현

backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/GetReservationsUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/ReservationQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/projection/UserReservationProjection.java
- #162 
- 조회 결과에 중복된 필드가 여러개 반환되는 버그가있어서 수정할 예정입니다.
=> [BE] 예매 조회시 BusScheduleId도 조회하도록 변경

backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/GetReservationsUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/ReservationQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/projection/UserReservationProjection.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/exchanges/enums/ReservationCategory.java
- #167 
- JPQL의 SELECT절에 DISTINCT 키워드를 붙여서 중복 튜플 제거,
- user.home.stationName으로 찾아오는것이아닌, location.stationName으로 찾아오도록 최적화
- type이 TO_SCHOOL이면 예상 도착시간이므로 arrival_time을 가져오고, type이 TO_HOME일때는 예상 출발시간이므로 departure_time을 가져와야하는데, 이런 분기 처리가 안되어있음을 확인했습니다.
=> [BE] 예매 내역 조회 중복 튜플 반환했던 버그 해결

backend/src/main/java/com/ddbb/dingdong/application/usecase/bus/GetAvailableBusLine.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/BusScheduleQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/BusStopQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/projection/AvailableBusStopProjection.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/projection/BusReservedSeatProjection.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/BusStopQueryService.java, backend/src/main/java/com/ddbb/dingdong/domain/user/repository/UserQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/user/repository/projection/HomeStationProjection.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/bus/BusController.java
- #133
- 방향과 시간을 입력으로 하여, "함께 타기" 가능한 정류장 정보들을 조회하는 API를 구현합니다.
- 정류장 정보에는 버스 이름, 정류장 위치, 정류장 이름, 해당 노선에 예약한 인원 수, 버스 가용 인원 수가 포함됩니다.
- 사용자가 지정한 탑승지 위치를 기준 1km 이내에 있고, 같은 노선의 정류장이 여러 개 있다면 제일 가까운 하나의 정류장만 조회합니다.
- 조회되는 정류장은 그 시간 기준 아직 출발하지 않은 노선의 정류장만 조회합니다.
- 노선에 예약된 인원 수는 ticket 컬럼의 개수 기준으로 가져옵니다. (데드락 회피 및 동시성 성능 확보 목적)
=> [BE] 시간대별 정류장 조회 API

backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/GetReservationsUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/routing/CreateRouteUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/ReservationQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/projection/UserReservationProjection.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/entity/Path.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/routing/BusRouteCreationService.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/routing/util/TmapRouteOptimizationDTOConverter.java
=> [BE] tmap api이용한 경유지 최적화 코드 수정

backend/src/main/java/com/ddbb/dingdong/application/usecase/notification/GetNotificationsUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/notification/repository/projection/NotificationProjection.java
JPA Projection에서는 get~~() 처럼 get으로 시작해야하는데,
실수로 startStationName()으로 get을 빼먹어 버그가 발생하였고 이를 수정하였음.
=> [BE] 긴급 수정 Projection 코드버그 수정

backend/src/main/java/com/ddbb/dingdong/domain/payment/repository/WalletProjectionRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/payment/repository/projection/FailedRefundProjection.java, backend/src/main/java/com/ddbb/dingdong/domain/payment/service/RetryScheduler.java
- reservation status가 FAIL_ALLOCATED 인데, usageHistory에 해당 reservation id가 REFUND인것이 없는 것을 환불이 실패한 것으로 간주합니다.
-  `@Schedule`을 사용해 30분마다 해당 list를 projection하여 환불 실패된 내역을 전부 찾아옵니다.
- 내역을 3분할하여, 3개의 쓰레드에서 병렬처리를 시키도록 하였습니다.
=> [BE] 30분마다 환불 실패한 내역 찾아 retry하는 scheduler 구현

backend/src/main/java/com/ddbb/dingdong/application/usecase/user/FastSignUpUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/user/repository/UserRepository.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/admin/temp/AdminUserTestController.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/admin/temp/dto/FastSignUpDTO.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/admin/temp/dto/GetUserInfoDTO.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/admin/temp/dto/UserHomeUpdateDTO.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/auth/exchanges/SignUpRequestDto.java
- #197 
- 유저의 정류장 위치를 관리자 마음대로 바꿀 수 있는 test 편의용 API를 구현했습니다.
- 유저의 정류장 위치를 관리자 마음대로 넣어 새 유저를 만들 수 있는 test 편의용 API를 구현했습니다.
- 모든 유저 정보를 조회할 수 있는 test 편의용 API를 구현했습니다.
모든 test 편의용 API들은 AdminUserTestController에 구현하였으며 운영 시작 할 때에는 비활성화 또는 제거될 예정입니다.
=> [BE] 데이터를 마련하기 위한 API 구현

backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/MakeGeneralReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/MakeTogetherReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/auth/encrypt/Token.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/auth/encrypt/TokenErrors.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/auth/encrypt/TokenManager.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/auth/encrypt/TokenRepository.java
- 현재는 중복 결제만 막기위해 이러한 기능을 도입하였습니다.
- 그러나 토큰이 무한히 쌓이는 문제가 발생할것같고, 이를 30분마다 삭제하는 배치작업도 현재 우리서버에 띄우기는 부담스러운 상황입니다.
- 차선책으로, 결제 로그 테이블에 결제 token 컬럼을 추가하고, 결제할때마다 해당 토큰값을 로그 테이블에 함께 저장합니다. 추후에 결제시 해당 토큰컬럼이 있는지 확인하는 방식으로 검증한다면 추가 테이블 생성없이 구현할 수 있을 것 같습니다. (이에 대해 어떤 생각이신지 의견을 묻고 싶어요 @ji-woong-song @popopy0412)
- 결제 로그가 많이 쌓일 경우를 대비해, 결제로그의 token 컬럼에 인덱스를 부여하는 방식으로 성능 비교를 해보고 도입하면 될 것 같습니다.
=> [BE] 한 토큰으로 중복 결제하는 문제 해결

backend/src/main/java/com/ddbb/dingdong/application/usecase/bus/GetBusStopLocationUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/BusScheduleQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/projection/BusStopLocationProjection.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/BusErrors.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/bus/BusController.java
- #196 
- 버스 스케쥴 아이디를 path variable로 주면 그 운행표에 타야할 버스 정류장 위치를 반환합니다
- 홈 화면 / 예약 내역 화면에서 필요 없어서 전달하지 않았던 버스 정류장 위치 정보를 조회하는 API 입니다.
- 실시간 버스 위치 확인 및 경로 확인 페이지에서 필요하여 구현했습니다.
=> [BE] 유저가 타야할 정류장 정보 조회 API 구현

backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/ReservationQueryRepository.java
- 페이지네이션을 처리할떄 사진과 같은 에러메세지가 출력되는것을 확인하였습니다.
<br><br><br>
sort는 아래와같이 ORDER BY절에서 사용하고 있었고, 오타도 없고 아무런 이상이없었는데 :sort를 바인딩하지 못했다는 오류가 나는것이 이상했습니다.<br>
<br><br><br>
페이지네이션처리를할때, 내부적으로 총 두번의 쿼리가 필요합니다.
1. 페이지 만큼의 데이터를 가져오는 select 문
2. 총 elements를 확인하는 count 쿼리 문
JPA에서 (2)번을 처리할때 **내부적으로 ORDER BY를 제거하고 쿼리를 실행한다고 합니다** 
ORDER BY를 제거하면서, `@Param("sort") int sort` 로 사용되었던 쿼리파라미터가 사용되지않게되고, binding실패로 count 쿼리 자체가 에러가 나서 실행되지 않게됩니다.
그렇게되면 totalElements의 값에, 현재 페이지된 리스트의 elements수가 들어가게되어 해당 문제가 발생하는것이었습니다.
즉, 메인 쿼리와 함께 전달된 모든 파라미터(userId, category, sort)를 count 쿼리에도 바인딩하려 시도하는데,
count 쿼리에는 실제로 :sort가 존재하지 않으므로 바인딩 시점에 "No parameter named ':sort'" 오류가 발생시키는 것이었습니다.
JPA에서 @Query 어노테이션에 countQuery를 명시적으로 지정하면, 페이징을 위해 전체 개수를 계산할 때 자동으로 생성되는 count 쿼리 대신 해당 countQuery를 그대로 사용합니다.
즉, <br>
<br>
과 같이 …
=> [BE] 예매 내역 조회 페이지네이션에서 totalElements를 잘못 가져오는 버그 수정

backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/ReservationController.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/exchanges/ReservationCancelDTO.java
- requestbody로 전달하던 reservationId를 PathVariable로 대체
- 기존 reservationCancelDTO는 pathvariable로 대체되어, 파일삭제
=> [BE] 예매 취소 url 변경

backend/src/main/java/com/ddbb/dingdong/ApplicationInitializer.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/user/FastSignUpUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/auth/service/AuthManagement.java, backend/src/main/java/com/ddbb/dingdong/domain/user/entity/User.java, backend/src/main/java/com/ddbb/dingdong/domain/user/entity/vo/Role.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/auth/AuthUser.java
- Application initializer에서, admin 전용 계정을 하나 더 추가하였습니다
- Role은 `ADMIN`, `USER` 두가지 타입만 존재합니다.
- 아직 Role에따른 api 인가는 구현하지 않은 상태입니다.
=> [BE] User 테이블에 Role 추가

src/main.tsx, src/pages/BusBooking/CustomRouteBooking/page.tsx, src/pages/BusBooking/FixedRouteBooking/page.tsx, src/pages/BusBooking/FixedRouteBookingSelectBus/components/BottomModal/index.tsx
- 함께 타기 예매 정보 세션스토리지 추가
- 모달 계속 html에 추가되는 문제 수정 완료 했습니다!
세션 스토리지에 추가될 형태는 아래와 같습니다. [노션에도 반영](https://www.notion.so/bside/FE-URL-19a220202735807ca4f9db5af6825741?pvs=4)해두었어요!
```
'/fixed-bus-select-bus': 
{
direction: "TO_SCHOOL", 
timeSchedule: '2025-02-20T23:00:00.000Z',
busId: 1,
busStopName: "버스 정류장이름"
};
```
=> [FE] - 함께 타기 예매 정보 세션스토리지 추가, 모달 계속 html에 추가되는 문제 수정

backend/src/main/java/com/ddbb/dingdong/application/usecase/bus/GetAvailableBusLine.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/BusStopQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/projection/AvailableBusStopProjection.java
=> [BE] 함께타기 예매에서 탑승 가능한 버스 조회시, 버스 정류장 ID도 반환하도록 수정

backend/src/main/java/com/ddbb/dingdong/application/usecase/notification/GetNotificationsUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/GetReservationsUseCase.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/notification/NotificationController.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/ReservationController.java
- #244
```
"page": {
"size": 2,
"number": 0,
"totalElements": 2,
"totalPages": 1
}
```
=> [BE] Page를 그대로 직렬화 했을때 직렬화에 실패하는 버그 해결

backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/auth/exchanges/SignUpRequestDto.java
```java
@Data
public class SignUpRequestDto {
private String name;
private String email;
private String password;
private Home home;
private Long schoolId;
@Data
@AllArgsConstructor
public static class Home {
private Double houseLatitude;
private Double houseLongitude;
private String houseRoadNameAddress;
}
}
``` 
기존 코드에서는 `@AllArgsConstructor` 어노테이션을 붙이는데,
이렇게되면 기본 생성자가 사라져서 Jackson의 역 직렬화가 실패합니다.
```java
@Data
public class SignUpRequestDto {
private String name;
private String email;
private String password;
private Home home;
private Long schoolId;
@Data
@AllArgsConstructor
@NoArgsConstructor
public static class Home {
private Double houseLatitude;
private Double houseLongitude;
private String houseRoadNameAddress;
}
}
``` 
`@AllArgsConstructor`를 어드민 테스트기능에서 직접 사용하고있다고 하여, …
=> [BE] 회원가입 api 호출시 RequestDTO로 역직렬화 안되는 버그 수정

backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/GetReservationsUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/GetUserBusScheduleInfoUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/ReservationQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/projection/UserReservationProjection.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/BusScheduleManagement.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/ReservationController.java
- 기존 Bus 테이블의 필드인 name을 가지고 버스이름을 그대로 보여주었는데, primary key를 활용하여 버스 01, 버스 02 등으로 이름을 만들어서 반환하도록 변경하였습니다.
- 기존 Bus 테이블의 Name은 모두 "가상 버스" 로 통일합니다.
=> [BE] 버스 이름 할당 방식 변경

backend/src/main/java/com/ddbb/dingdong/application/usecase/bus/StopBusUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/routing/CreateRouteUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/BusErrors.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/simulator/BusSubscriptionLockManager.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/simulator/subscription/BusSubscriptionManager.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/simulator/subscription/StoppableLock.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/simulator/subscription/subscriber/CancelableSubscriber.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/notification/WebPushNotificationEventListener.java, backend/src/test/java/com/ddbb/dingdong/bus/BusSimulatorTest.java
- #155 
- #26 
-  구독 취소 시 발행자가 없는 구독자가 구독 해제할 때 subscription이 null 인 경우 NullPointerException을 던지고 lock을 해제하지 않은 채 종료 됨
- Map에서 락을 제거하기 전에 락 상태를 업데이트하고, 락에 대기 중인 모든 스레드들이 종료되길 기다렸다가 락을 제거함
- 명시적인 락 관리자를 도입하여 구독자가 락을 만들면서 진입하지 않도록 함
- 명시적으로 try-catch-finally 문을 도입하여 예상치 못한 예외에도 반드시 락을 풀도록 함
=> [BE] 웹 소켓 구독 버그 수정

backend/src/main/java/com/ddbb/dingdong/ApplicationInitializer.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/MakeTogetherReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/RequestTogetherReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/notification/repository/NotificationQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/service/ReservationManagement.java
=> [BE] 함께타기 요청/결제 시, 48시간 내외임을 검증하던 로직 제거 및 알람 버그 수정

backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/RequestTogetherReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/error/ReservationInvalidParamErrors.java
=> [BE] 함께 타기 예매 시도 시, 누락된 필드에 대한 Null check 검사 기능 구현

backend/src/main/java/com/ddbb/dingdong/application/usecase/bus/GetAvailableBusLine.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/bus/GetBusSchedulesUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/ReservationQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/BusStopQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/projection/AllAvailableBusStopProjection.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/projection/AvailableBusStopProjection.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/BusStopQueryService.java, backend/src/main/java/com/ddbb/dingdong/domain/user/repository/UserQueryRepository.java
- #262 
1. 정말로 탑승 가능한 시간대만 조회하도록 탑승 가능 시간대 조회 API 변경
2. 버스 이름을 알맞은 형식에 맞게 응답하도록 수정
3. 운행 종료된 예매의 경우 보여지지 않도록 변경
=> [BE] 버스 스케쥴 조회 시 개인이 탈 수 있는 기록이 존재할 경우만 조회하도록 수정

backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/ReservationQueryRepository.java
=> [BE] 예매내역 조회에서 카테고리가 HOME일때, PENDING상태인 예매를 못 가져오는 버그 수정

backend/.database/schema.sql, backend/src/main/java/com/ddbb/dingdong/ApplicationInitializer.java, backend/src/main/java/com/ddbb/dingdong/domain/auth/service/AuthManagement.java, backend/src/main/java/com/ddbb/dingdong/domain/notification/service/NotificationEventListener.java, backend/src/main/java/com/ddbb/dingdong/domain/payment/entity/Wallet.java, backend/src/main/java/com/ddbb/dingdong/domain/payment/entity/vo/DingdongMoneyUsageType.java
- notification type에 'WELCOME_MONEY_CHARGE' 타입 추가
- 첫 가입 딩동머니를 5만원에서 3만원으로 수정 (너무 과한거같아서 30일치만 ..)
- initializer에서 usecase를 호출하도록 코드 수정 -> 시연용 테스트계정 비밀번호를 Abcd1234!@로 변경 (맨앞에 대문자로 수정)
- 가입시 자동으로 dingdong money history table에 3만원 추가되었다는 내역을 저장
=> [BE] 첫 가입 딩동머니 충전 내역을 히스토리 테이블에 자동 추가하도록 변경

backend/src/main/java/com/ddbb/dingdong/application/usecase/bus/GetAvailableBusLine.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/bus/GetBusSchedulesUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/ReservationQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/BusStopQueryService.java
- #293 
- 예약 내역에서 취소 되지 않은 예매 내역의 딩동 타임을 조회하고, 이 조회한 내역을 바탕으로 겹치는 시간을 필터링합니다.
- 버스 시간대 조회, 버스 정류장 조회 모두 적용했습니다.
=> [BE] 버스 정류장 추천 시 예약한 시간을 제외하는 조건 추가

backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/MakeGeneralReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/RequestGeneralReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/ReservationQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/service/DuplicatedReservationError.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/service/ReservationManagement.java
- #302 
- 버스 예매하기 예매 정보 중에 어떤 날짜 때문에 겹치는 건지 명시적으로 알려주는 예외를 던지도록 변경
- 일단은 예외를 메시지로 전달하는데 프론트 분들과 소통 후 예외 메시지를 다르게 반환할 수 있음.
=> [BE] 중복 예약된 예약 건수에 대한 자세한 알림 메시지

backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/ReservationQueryRepository.java
ReservationQueryRepository에서, 
`...(:category = 1 AND CAST(r.status AS STRING) = 'ALLOCATED' AND bs_arrival.status != 'ENDED')
로 쿼리문을 수정
`
=> [BE] 예매 내역 조회에서 '배차완료' 카테고리가 '운행 종료'도 가져오는 문제 수정

backend/src/main/java/com/ddbb/dingdong/application/usecase/bus/StopBusUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/BusScheduleQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/BusPublishService.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/BusSubscribeService.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/simulator/BusSimulatorFactory.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/simulator/BusSubscriptionLockManager.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/simulator/subscription/BusSubscriptionManager.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/simulator/subscription/StoppableLock.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/subscription/BusSubscriptionManager.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/subscription/UserSubscription.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/subscription/publisher/PeriodicBusPublisher.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/subscription/source/BusSimulator.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/subscription/subscriber/CancelableSubscriber.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/subscription/subscriber/SocketSubscriber.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/subscription/subscriber/StubConsoleSubscriber.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/lock/StoppableLock.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/notification/NotificationMessageFormatter.java, backend/src/test/java/com/ddbb/dingdong/bus/BusSimulatorTest.java, backend/src/test/java/com/ddbb/dingdong/infrastructure/bus/simulator/BusSubscriptionLockManagerTest.java
- 서버 시작 시 DB에 저장된 버스(READY, RUNNING) 에 대한 구독 락을 다시 복구하는 기능을 구현했습니다.
- StoppableLock 이 Busy Waiting 하지 않고 시그널 기반으로 깨어나도록 구현했습니다.
=> [BE] Lock 로더

backend/src/main/java/com/ddbb/dingdong/application/usecase/clustering/CreateClusterUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/routing/CreateRouteUseCase.java
- 같은 시간 & 방향의 버스를 여러번 배차할경우, 이전 클러스터라벨과 겹쳐서 에러가 발생합니다.
- 이미 생성된 location의 클러스터라벨을 "DONE"으로 명시적으로 변경해 해결하였습니다.
=> [fix] 이미 Path가 생성된 location은 클러스터 라벨을 "DONE"이라고 변경하기

backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/ReservationQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/ReservationRepository.java
- 하교시, 다른 유저가 예매한 시간을 예매하면 중복되었다고 나오는 버그가 있었습니다.
- 마지막 AND 쿼리를 크게 괄호로 묶었어야 했는데 빠져서 발생한 버그였습니다.
=> [BE] 일반예매시 중복 예약을 체크하는 쿼리에서, 괄호가 빠져서 다른 결과를 나왔던 버그 수정

backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/GetReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/ReservationQueryRepository.java, backend/src/main/java/com/ddbb/dingdong/presentation/endpoint/reservation/ReservationController.java
/api/users/reservations/:reservationId
=> [BE] reservationId로 단일 예매내역을 조회하는 API추가 

backend/src/main/java/com/ddbb/dingdong/domain/notification/service/NotificationEventListener.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/subscription/subscriber/SocketSubscriber.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/webSocket/SocketMessageSender.java
- #324 
1. 버스 출발 시 예약 아이디를 전송하도록 NotificationEventListener의 구현을 변경했습니다.
2. 소켓 전송 로직을 담당하는 객체를 만들어 책임을 분리했습니다.
3. 구독자가 소켓전송 시 소켓이 닫혀있다면 전송을 하지 않도록 변경했습니다.
=> [BE] 버스 출발 시 예매 아이디를 전송 로직 추가 #324

index.html, public/manifest.json, src/components/Modal/styles.ts, src/pages/Auth/Login/index.tsx, src/pages/Auth/LoginHome/index.tsx, src/pages/Auth/Signup/UserInfo/index.tsx, src/pages/BusBooking/CustomRouteBooking/components/CalendarView/index.tsx, src/pages/BusBooking/CustomRouteBooking/page.tsx, src/pages/TimetableManagement/components/TimePicker/index.tsx, src/webPushNotification/settingFCM.ts, vite.config.ts
#326 
FCM 웹 푸시 알림이 아이폰에서는 알림 허용 창을 확인 할 수 없어서, 구현 방법을 알아보았습니다. 크게 2가지가 필요합니다.
- PWA 셋팅 (manifest.json, html 헤더에 json파일 추가)
- 클릭 이벤트를 통한 알림 허용 요청 처리
- 유저가 홈 화면에 추가
- https에서만 확인할 수 있으므로, 배포가 되어야 작동여부를 볼 수 있을 것 같습니다.
=> [FE] - ios FCM알림 오도록 설정 구현 & 데모데이 QA 반영 & 번들 사이즈 줄이기

backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/MakeTogetherReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/RequestTogetherReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/routing/CreateRouteUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/service/ReservationConcurrencyManager.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/service/ReservationErrors.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/service/ReservationManagement.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/BusScheduleRepository.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/cache/SimpleCache.java, backend/src/main/resources/application-local.yml, backend/src/test/java/com/ddbb/dingdong/reservation/ReservationConcurrencyTest.java, backend/src/test/resources/application.yml
1. SimpleCache를 이용하여, CreateRouteUseCase를 실행할 때 생성되는 BusSchedule의 id를 통해 남은 좌석수를 크기로 가지는 Semaphore와 Lock을 저장하도록 구현했습니다. (함께타기는 예매가 48시간 동안만 이루어지므로, 만료 기간을 2일로 설정)
2. 예매를 시도하는 사용자는 SimpleCache에 Key=userId, Value=busScheduleId, 만료기간=5분을 가지는 CacheEntry로 저장됩니다.
- 1번 스케쥴을 예매 신청을 하고, 2번 스케쥴에 결제를 시도하는 행위를 막기 위해 Value에 busScheduleId를 설정했습니다.
3. 예매 시도 시, 중복 예매와 유효하지 않은 입력 값 검증이 끝난 후에 실질적으로 예매를 들어가는 부분부터 Semaphore를 얻도록 구현했습니다.
- 만료 기간이 지났거나, SimpleCache에 의해 자동으로 Clean up되는 경우 세마포어를 반환하도록 했습니다.
4. 결제 시도 시, Bus Schedule 별로 관리되는 Lock을 얻어 실질적인 에매 확정 작업을 지은 후, Lock을 unlock하도록 구현했습니다.
1. 함께타기 예매 동시성 테스트
2. SimpleCache CleanUp 작업 시, 세마포어 반환 테스트
=> [BE] 함께 타기 예매에 대한 동시성 보장

src/pages/Auth/LoginHome/index.tsx, src/webPushNotification/settingFCM.ts
#326 
문제 : ios 브라우저에서 서비스 링크 접속시 흰화면이 나오는 문제가 발생했습니다.
원인을 찾고 해결하고자 수정을 했습니다.
=> [FE] - FCM 알림 ios 적용 처리 :  ios 브라우저 화면에서 서비스가 흰화면으로 보이는 문제 해결

backend/src/main/java/com/ddbb/dingdong/domain/reservation/repository/ReservationQueryRepository.java
- countquery에서, SELECT COUNT(r)이 실수로 빠졌던 버그 수정
=> [BE] count query에서 SELECT문이 빠졌던 것 수정

backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/MakeTogetherReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/service/ReservationConcurrencyManager.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/cache/SimpleCache.java
- 함께타기에서 예약이 확정되면, 세마포어를 놓지 말아야하는데 세마포어를 놓아서 좌석 수가 제대로 반영이 안되는 버그
- 캐시에서 제거될 때 세마포어를 놓는 메소드와, 캐시에서 제거될 때 세마포어를 놓지 않는 메소드를 분기해서 해결하였습니다.
=> [BE] 함께 타기 예약이 확정되면, 세마포어를 놓지 않고 계속 유지하도록 변경

backend/src/main/java/com/ddbb/dingdong/application/usecase/bus/StartBusUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/MakeTogetherReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/RequestTogetherReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/reservation/service/ReservationConcurrencyManager.java, backend/src/test/java/com/ddbb/dingdong/reservation/ReservationConcurrencyTest.java, backend/src/test/resources/application.yml
=> [BE] 버스 출발 후 사용자의 예매 및 결제 시도 차단

backend/src/main/java/com/ddbb/dingdong/domain/notification/service/NotificationEventListener.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/BusPublishService.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/BusSubscribeService.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/service/RepositoryRouteSegmentProvider.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/subscription/BusSubscriptionManager.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/subscription/UserSubscription.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/subscription/publisher/PeriodicBusPublisher.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/subscription/source/BusSimulator.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/subscription/subscriber/SocketSubscriber.java, backend/src/main/java/com/ddbb/dingdong/infrastructure/bus/subscription/subscriber/StubConsoleSubscriber.java
- #355 
- 버스 시뮬레이터가 중간 위치 부터 출발하는 버그를 수정했습니다
- 버스 위치 데이터를 바이너리 형식으로 전송하도록 변경했습니다.
- Subscriber의 구독 버퍼 크기를 1로 줄였습니다. (데이터가 드랍되더라도 최신 데이터가 중요하기 때문)
=> [BE] 소켓 전송 최적화 및 메시지 추가, 시뮬레이션 버그 수정

backend/src/main/java/com/ddbb/dingdong/application/usecase/reservation/MakeTogetherReservationUseCase.java, backend/src/main/java/com/ddbb/dingdong/domain/transportation/repository/BusScheduleRepository.java
초기에 티켓의 수를 가져와 남은 좌석 수를 판단하므로 필요없는 쿼리문이기에 삭제했습니다.
=> [BE] Hotfix: 버스 스케쥴 테이블 내 남은 좌석 수 감소 시키는 쿼리문 삭제

frontend/public/firebase-messaging-sw.js, frontend/src/pages/Auth/Components/Dropdown/index.tsx, frontend/src/pages/Auth/Components/Dropdown/styles.ts
#387 
- url이 혹시 존재하지 않을 때를 대비해서, url 존재하지 않는다면 URL 링크로 이동하도록 수정했습니다.
- +) ios 파란색 폰트 부분이 나오는 문제 -> gray100 색을 추가하여 수정했습니다.
=> [FE] - fcm 푸시 알림을 클릭했을 때, 알림 내역 화면으로 이동하도록 검증 조건문 추가.
